apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f spv-docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: lsup-system-messages
  name: lsup-system-messages
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "61411"
      protocol: TCP
      port: 61411
      targetPort: 61411
  selector:
    io.kompose.service: lsup-system-messages
status:
  loadBalancer: {}
