apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f spv-docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: lsup-link-rest-agent
  name: lsup-link-rest-agent
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "8083"
      protocol: TCP
      port: 8083
      targetPort: 8083
  selector:
    io.kompose.service: lsup-link-rest-agent
status:
  loadBalancer: {}
