apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f spv-docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: igs-monitor
  name: igs-monitor
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "6666"
      protocol: TCP
      port: 6666
      targetPort: 6666
  selector:
    io.kompose.service: igs-monitor
status:
  loadBalancer: {}
