apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f spv-docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: lsup-system-messages
  name: lsup-system-messages
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: lsup-system-messages
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f spv-docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/supervision: "true"
        io.kompose.service: lsup-system-messages
    spec:
      imagePullSecrets:
      - name: {{ .Values.docker.repository }}
      containers:
        - image: {{ .Values.lsub.system.message.image }}
          name: lsup-system-messages
          resources: {}
      restartPolicy: Always
status: {}
